GET http://localhost:8091/todos
X-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHBpcmluZ1RpbWUiOjE2MjExNjI0MjE0MzIsInN1YiI6IjEiLCJyb2xlIjoiQURNSU4iLCJzdGF0ZSI6IkFDVElWRSIsImVtYWlsIjoiZGFuQGdtYWlsLmNvbSJ9.odkAARwmOP-d6JQSPocjvQxRDENfNYpFk2wmzhBER2g

###
POST http://localhost:8091/todos
Content-Type: application/json

{
  "text": "hello world!",
  "id": "3"
}
###
PUT  http://localhost:8091/todos
Content-Type: application/json

{
  "text": "hello world! (edited)",
  "id": "3"
}
###
DELETE  http://localhost:8091/todos?todoId=3
###

POST http://localhost:8091/login
Content-Type: application/json

{
  "email": "dan@gmail.com",
  "password": "qwerty007"
}

###

GET http://localhost:8091/logout
X-TOKEN: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHBpcmluZ1RpbWUiOjE2MjExNjIyMjAwNjUsInN1YiI6IjEiLCJyb2xlIjoiQURNSU4iLCJzdGF0ZSI6IkFDVElWRSIsImVtYWlsIjoiZGFuQGdtYWlsLmNvbSJ9.g3DS-YABYDjB_WGVytpe2-yyWobWXXyZavYM1kfY39A

###

POST http://localhost:8091/users/1/block

###